package py.com.icarusdb.demo.invoice.model;

// Generated Feb 8, 2014 3:17:30 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.GeneratedValue;

/**
 * InvoiceDetailId generated by hbm2java
 */
@Embeddable
public class InvoiceDetailId implements java.io.Serializable
{
    /**
     * 
     */
    private static final long serialVersionUID = 6840247479287831649L;
    
    private Long id;
    private Long invoice;

    public InvoiceDetailId()
    {
    }

    public InvoiceDetailId(Long id, Long invoice)
    {
        this.id = id;
        this.invoice = invoice;
    }

    @GeneratedValue
    @Column(name = "id", nullable = false)
    public Long getId()
    {
        return this.id;
    }

    public void setId(Long id)
    {
        this.id = id;
    }

    @Column(name = "invoice", nullable = false)
    public Long getInvoice()
    {
        return this.invoice;
    }

    public void setInvoice(Long invoice)
    {
        this.invoice = invoice;
    }

    public boolean equals(Object other)
    {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof InvoiceDetailId))
            return false;
        InvoiceDetailId castOther = (InvoiceDetailId) other;

        return (this.getId() == castOther.getId()) && (this.getInvoice() == castOther.getInvoice());
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + this.getId().intValue();
        result = 37 * result + this.getInvoice().intValue();
        return result;
    }

}
