package py.com.icarusdb.demo.invoice.model;

// Generated Feb 8, 2014 3:17:30 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Properties;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import py.com.icarusdb.entity.EntityInterface;
import py.com.icarusdb.util.IDBProperties;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name = "item", schema = "public")
public class Item implements EntityInterface
{
    /**
     * 
     */
    private static final long serialVersionUID = 4225551365571383009L;


    private static final String GENERATOR = "ITEM_ID_GENERATOR";


    private Long id;
    private String description;
    private String code;
    private String barcode;
    private Integer minimunStock;
    private Set<InvoiceDetail> invoiceDetails = new HashSet<InvoiceDetail>(0);

    public Item() {}
    
    @Id
    @SequenceGenerator(name = GENERATOR, sequenceName = "public.item_id_seq", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = GENERATOR)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId()
    {
        return this.id;
    }

    public void setId(Long id)
    {
        this.id = id;
    }

    @Column(name = "description", nullable = false, length = 200)
    public String getDescription()
    {
        return this.description;
    }

    public void setDescription(String description)
    {
        this.description = description;
    }

    @Column(name = "code", nullable = false, length = 10)
    public String getCode()
    {
        return this.code;
    }

    public void setCode(String code)
    {
        this.code = code;
    }

    @Column(name = "barcode", length = 20)
    public String getBarcode()
    {
        return this.barcode;
    }

    public void setBarcode(String barcode)
    {
        this.barcode = barcode;
    }

    @Column(name = "minimun_stock")
    public Integer getMinimunStock()
    {
        return this.minimunStock;
    }

    public void setMinimunStock(Integer minimunStock)
    {
        this.minimunStock = minimunStock;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "item")
    public Set<InvoiceDetail> getInvoiceDetails()
    {
        return this.invoiceDetails;
    }

    public void setInvoiceDetails(Set<InvoiceDetail> invoiceDetails)
    {
        this.invoiceDetails = invoiceDetails;
    }

    @Override
    @Transient
    public Properties getProperties()
    {
        Properties properties = new IDBProperties();
        properties.put("id" , id);
        return properties;
    }

}
