package py.com.icarusdb.demo.invoice.model;

// Generated Feb 8, 2014 3:17:30 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SystemUser generated by hbm2java
 */
@Entity
@Table(name = "system_user", schema = "public")
public class SystemUser implements java.io.Serializable
{
    /**
     * 
     */
    private static final long serialVersionUID = -1801439191303066926L;
    
    private Long id;
    private String username;
    private String password;

    public SystemUser()
    {
    }

    public SystemUser(Long id, String username, String password)
    {
        this.id = id;
        this.username = username;
        this.password = password;
    }

    @Id
    @GeneratedValue
    @Column(name = "id", unique = true, nullable = false)
    public Long getId()
    {
        return this.id;
    }

    public void setId(Long id)
    {
        this.id = id;
    }

    @Column(name = "username", nullable = false, length = 10)
    public String getUsername()
    {
        return this.username;
    }

    public void setUsername(String username)
    {
        this.username = username;
    }

    @Column(name = "password", nullable = false, length = 50)
    public String getPassword()
    {
        return this.password;
    }

    public void setPassword(String password)
    {
        this.password = password;
    }

}
